a="mother Board no:\t007"
b=('M','o','t','h','e','r')
print(a.capitalize())
print(a.casefold())
print(a.center(30,'*'))
print(a.count('o'))
print(a.encode())
print(a.endswith('g'))
print(a.expandtabs(12))
print(a.find('oa'))
print('Hey there {0} your binary conversion is {0:b}'.format(1234))
print(a.index('no'))
print(a.isalnum())
print(a.isalpha())
print(a.isascii())
print(a.isdecimal())
print(a.isdigit())
print(a.isidentifier())
print(a.islower())
print(a.isnumeric())
print(a.isprintable())
print(a.isspace())
print(a.istitle())
print(a.isupper())
print('-'.join(b))
print(a.ljust(30),'$$$$$$$$$$')